language: haskell
env:
  - GHC_VERSION=7.8
  #- GHC_VERSION=7.6
  #- GHC_VERSION=7.4

before_install:
  - date
  - echo $PATH
  - which cabal
  - which runghc
  - dpkg -l cabal-install
  - dpkg -S /usr/bin/cabal
  - sudo apt-get update
  - cat /home/travis/.cabal/config
  - find /usr/local/ghc/*/bin -type f -ls
install:
  - sudo apt-get --purge remove cabal-install
  - apt-cache show cabal-install
  - sudo apt-get install haskell-platform haskell-platform-prof haskell-platform-doc cabal-install
  - dpkg -l ghc
  - dpkg -l cabal-install
  - echo install
script:
  - echo script
after_script:
  - date
