language: haskell
ghc:
  - 7.8
  - 7.6
  - 7.4

before_install:
  - date
  - echo $PATH
  - which cabal
  - which runghc
  - cat /home/travis/.cabal/config
  - find /usr/local/ghc/*/bin -type f -ls
install:
  - echo install
script:
  - echo script
after_script:
  - date
