language: haskell
env:
  - GHC_VERSION=7.8
  - GHC_VERSION=7.6
  - GHC_VERSION=platform

before_install:
  - date
  - echo $PATH
  - which cabal
  - which runghc
  - dpkg -l cabal-install
  - dpkg -S /usr/bin/cabal
  - sudo apt-get update
  - cat /home/travis/.cabal/config
  - find /usr/local/ghc/*/bin -type f -ls
install:
  - case "$GHC_VERSION" in
      platform)
        sudo apt-get --purge remove cabal-install ;
        sudo apt-get install haskell-platform haskell-platform-prof haskell-platform-doc cabal-install=0.14.0-2 ;
        export PATH=/usr/bin:$PATH
        ;;

      *)
        export PATH=/usr/local/ghc/$(ghc_find $GHC_VERSION)/bin:$PATH
        ;;
    esac
  - dpkg -l ghc
  - dpkg -l cabal-install
  - which ghc
  - which cabal-install
  - echo install
script:
  - echo script
after_script:
  - date
